name: Build Batch Release

on:
  push:
    branches:
      - release/**
jobs:
  build:
    name: Build gems
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Build gem source
      run:  ruby .scripts/batch_build.rb
    - name: Archive Artifacts
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: ${{ github.sha }}
        path: sentry*/*.gem
